backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master) 

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "public/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "Characters" # Used in routes, e.g., /admin/collections/blog
    label: "Character names" # Used in the UI


    files: "public/data/learning.json" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: name, name: name, widget: string }
      - {label: age, name: age, widget: number }
      