backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master) 

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "public/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Characters"
    name: "characters"
    files:
      - label: "About Character"
        name: "character"
        file: "public/data/learning.json"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Age, name: age, widget: number}
          